#!/bin/bash
usage() {
    echo "htpasswd [username] [password] [filename]"
}

# if less than two arguments supplied, display usage
if [  $# -le 2 ]
then
    usage
fi

# check whether user had supplied -h or --help . If yes display usage
if [[ ( $# == "--help") ||  $# == "-h" ]]
then
    display_usage
fi

if [ "$#" == 3 ]
then
    eval "printf $1:\$(openssl passwd -apr1 $2)\\\n >> $3"
fi
