#!/bin/bash
usage() {
    echo -e "\nhtpasswd [option] [username] [password]   (1st form)"
    echo -e "htpasswd [username] [password]            (2nd form)\n"
    echo -e "Options:"
    echo -e "\t-m, generate md5 passwords (default)"
    echo -e "\t-s, generate SHA1 passwords"
    echo -e "\t-c, generate CRYPT passwords"
    echo -e "\t-f, --file= append output to existing file\n"
    echo -e "If used without options, this script will return [username]:[md5 password hash]\n"
}

# check whether user had supplied -h or --help . If yes display usage
if [[ ( $# == "--help") ||  $# == "-h" ]]
then
    usage
fi

if [ $# -le 1 ]
then
    usage
fi

# if two arguments supplied, display username:md5 hash
if [  "$#" == 2 ]
then
    eval "printf $1:\$(openssl passwd -apr1 $2)\\\n"
fi

if [ $# -ge 3 ]
then
    while getopts ":f" opt; do
        case $opt in
            f)
                echo '-f was triggered' >&2
                eval "printf $1:\$(openssl passwd -apr1 $2)\\\n >> $3"
                ;;
            \?)
                echo "invalid option -$OPTARG" >&2
                ;;
        esac
    done
fi
